/* A polyfill for browsers that don't support ligatures. */
/* The script tag referring to this file must be placed before the ending body tag. */

/* To provide support for elements dynamically added, this script adds
   method 'icomoonLiga' to the window object. You can pass element references to this method.
*/
(function () {
    'use strict';
    function supportsProperty(p) {
        var prefixes = ['Webkit', 'Moz', 'O', 'ms'],
            i,
            div = document.createElement('div'),
            ret = p in div.style;
        if (!ret) {
            p = p.charAt(0).toUpperCase() + p.substr(1);
            for (i = 0; i < prefixes.length; i += 1) {
                ret = prefixes[i] + p in div.style;
                if (ret) {
                    break;
                }
            }
        }
        return ret;
    }
    var icons;
    if (!supportsProperty('fontFeatureSettings')) {
        icons = {
            'gold-coin': '&#xe9f2;',
            'earn': '&#xe9f3;',
            'left-point': '&#xe9f4;',
            'right-point': '&#xe9f5;',
            'tga': '&#xe9f6;',
            'percent': '&#xe9d0;',
            'dollar-o': '&#xe9d1;',
            'building-o': '&#xe9d2;',
            'cake': '&#xe9d3;',
            'cap': '&#xe9d4;',
            'car-o': '&#xe9d5;',
            'card-o': '&#xe9d6;',
            'charge': '&#xe9d7;',
            'crown-vip': '&#xe9d8;',
            'ding': '&#xe9d9;',
            'dinner': '&#xe9da;',
            'discount': '&#xe9db;',
            'drink': '&#xe9dc;',
            'endless': '&#xe9dd;',
            'evaluation': '&#xe9de;',
            'game': '&#xe9df;',
            'gift-40': '&#xe9e0;',
            'gold-word': '&#xe9e1;',
            'heart-40': '&#xe9e2;',
            'link-40': '&#xe9e4;',
            'massage': '&#xe9e5;',
            'new': '&#xe9e6;',
            'racket': '&#xe9e7;',
            'reading': '&#xe9e8;',
            'share-o': '&#xe9e9;',
            'sign': '&#xe9ea;',
            'silver-word': '&#xe9eb;',
            'taype': '&#xe9ec;',
            'tie': '&#xe9ed;',
            'up-arrow': '&#xe9ee;',
            'diamond-40': '&#xe9ef;',
            'wechat-o': '&#xe9f0;',
            'wifi-40': '&#xe9f1;',
            'check-c-o': '&#xe9ce;',
            'share-s-o': '&#xe9cf;',
            'menber-add': '&#xe9cc;',
            'menbers': '&#xe9cd;',
            'kingsilk-logo': '&#xe9cb;',
            'hand-heart': '&#xe9ca;',
            'about': '&#xe9c9;',
            'quotes-left': '&#xe9c7;',
            'quotes-right': '&#xe9c8;',
            'rhombus-o': '&#xe9c6;',
            'chat-smile-o': '&#xe9bb;',
            'shoppingcart-o': '&#xe9c5;',
            'calendar-sign': '&#xe9ba;',
            'Crown-o': '&#xe9bc;',
            'edit-pencil': '&#xe9bd;',
            'like-o': '&#xe9be;',
            'like': '&#xe9bf;',
            'live': '&#xe9c0;',
            'play': '&#xe9c1;',
            'spring': '&#xe9c2;',
            'suspend': '&#xe9c3;',
            'view': '&#xe9c4;',
            'share': '&#xe9b9;',
            'carton-sort': '&#xe9b6;',
            'bowknot': '&#xe900;',
            'handkerchief': '&#xe901;',
            'bedding': '&#xe902;',
            'baby': '&#xe903;',
            'sign-circular': '&#xe9b1;',
            'building': '&#xe9af;',
            'coupon-square': '&#xe9b0;',
            'pen，edit': '&#xe9ae;',
            'stats': '&#xe906;',
            'combine': '&#xe907;',
            'qr，code': '&#xe908;',
            'phone': '&#xe90c;',
            'other': '&#xe910;',
            'pyjamas': '&#xe911;',
            'pillow': '&#xe912;',
            'scarf': '&#xe913;',
            'bed，quilt': '&#xe914;',
            'all': '&#xe915;',
            'cart': '&#xe916;',
            'shelf': '&#xe917;',
            'mine': '&#xe918;',
            'plus': '&#xe919;',
            'aircondition': '&#xe91a;',
            'dryer': '&#xe91b;',
            'hot-water': '&#xe91c;',
            'net': '&#xe91d;',
            'tv': '&#xe91e;',
            'wifi': '&#xe91f;',
            'sterilization-o': '&#xe920;',
            'sterilization': '&#xe921;',
            'acarid-o': '&#xe922;',
            'acarid': '&#xe923;',
            'dry-o': '&#xe924;',
            'dry': '&#xe925;',
            'time': '&#xe9b8;',
            'time-o': '&#xe926;',
            'manage': '&#xe909;',
            'category': '&#xe928;',
            'store-service': '&#xe929;',
            'store': '&#xe92a;',
            'arrow_up': '&#xe92b;',
            'arrow_down': '&#xe92c;',
            'arrow_left': '&#xe92d;',
            'arrow_right': '&#xe92e;',
            'v-one': '&#xe975;',
            'v-three': '&#xe97b;',
            'v-two': '&#xe978;',
            'verified-o': '&#xe92f;',
            'verified': '&#xe930;',
            'diamond-o': '&#xe935;',
            'diamond-o-v': '&#xe939;',
            'carton': '&#xe940;',
            'caret-left': '&#xe983;',
            'caret-right': '&#xca;',
            'star-o': '&#xe97c;',
            'star': '&#xe942;',
            'sort': '&#xe936;',
            'sort-asc': '&#xe931;',
            'sort-desc': '&#xe932;',
            'sort-right-left': '&#xe970;',
            'question': '&#xe933;',
            'question-o': '&#xe949;',
            'msg': '&#xe934;',
            'chat': '&#xe937;',
            'location': '&#xe938;',
            'location-o': '&#xe93a;',
            'card': '&#xe93b;',
            'card-r': '&#xe93c;',
            'logo-word': '&#xe93d;',
            'logo-square': '&#xe984;',
            'logo-o': '&#xe986;',
            'success': '&#xe93e;',
            'selected-o': '&#xe93f;',
            'user-o': '&#xe941;',
            'user': '&#xe943;',
            'gift': '&#xe944;',
            'gift-o': '&#xe945;',
            'gift-o-1': '&#xe951;',
            'fileboard，down，': '&#xe904;',
            'order-close': '&#xe9b7;',
            'done': '&#xe953;',
            'file，order，manage': '&#xe90a;',
            'file，order': '&#xe90b;',
            'order': '&#xe946;',
            'order-o': '&#xe947;',
            'eye': '&#xe948;',
            'eye-o': '&#xe94a;',
            'point': '&#xe90f;',
            'r-selected': '&#xe94b;',
            'c-selected': '&#xe94c;',
            'r-unselected': '&#xe94d;',
            'c-unselected': '&#xe94e;',
            'r-close': '&#xe90e;',
            'delete': '&#xe94f;',
            'cancle': '&#xe950;',
            'exclamation-circle': '&#xe952;',
            'crown': '&#xe954;',
            'close-little': '&#xe955;',
            'close': '&#xe956;',
            'trash-can-o': '&#xe987;',
            'times- irregular-o': '&#xe979;',
            'timing': '&#xe957;',
            'timing-o': '&#xe958;',
            'dollar-symbol': '&#xe959;',
            'dollar': '&#xe95a;',
            'rmb-symbol': '&#xe973;',
            'rmb-square': '&#xe95b;',
            'money': '&#xe927;',
            'shopping-cart': '&#xe95c;',
            'shopping-cart-o': '&#xe95d;',
            'selected': '&#xe95e;',
            'edit-o': '&#xe95f;',
            'drawer-arrow-up': '&#xe960;',
            'delivery': '&#xe961;',
            'hand-bag': '&#xe962;',
            'edit': '&#xe963;',
            'drawer': '&#xe964;',
            'rotate': '&#xe965;',
            'plus-bold': '&#xe97a;',
            'minus': '&#xe985;',
            'loading': '&#xe966;',
            'coupon': '&#xe967;',
            'tag': '&#xe968;',
            'check': '&#xe969;',
            'heart-o': '&#xe96a;',
            'heart': '&#xe97f;',
            'telephone': '&#xe980;',
            'phone': '&#xe96b;',
            'rent-word': '&#xe96c;',
            'alipay': '&#xe96d;',
            'weixin': '&#xe96e;',
            'bell': '&#xe96f;',
            'more': '&#xe971;',
            'wallet，balance': '&#xe905;',
            'wallet': '&#xe972;',
            'link': '&#xe974;',
            'signal-tower': '&#xe976;',
            'quilt': '&#xe977;',
            'rent-order': '&#xe97d;',
            'house-o': '&#xe97e;',
            'retrofit': '&#xe981;',
            'water': '&#xe982;',
            'hourglass': '&#xe988;',
            'red-packets': '&#xe989;',
            'search': '&#xe98a;',
            'maintain': '&#xe98b;',
            'recovery': '&#xe98c;',
            'invoice': '&#xe98d;',
            'email': '&#xe98e;',
            'qrcode': '&#xe98f;',
            'bulb': '&#xe990;',
            'ti-word': '&#xe991;',
            'shopping-basket': '&#xe992;',
            'folder': '&#xe993;',
            'slogan-word': '&#xe994;',
            'bank-logo-ecitic': '&#xe995;',
            'bank-logo-boc': '&#xe996;',
            'bank-logo-abchina': '&#xe997;',
            'bank-logo-ccb': '&#xe998;',
            'bank-logo-czbank': '&#xe999;',
            'bank-logo-tccb': '&#xe99a;',
            'bank-logo-cib': '&#xe99b;',
            'bank-logo-cmbchina': '&#xe99c;',
            'bank-logo-icbc': '&#xe99d;',
            'bank-logo-bankofshanghai': '&#xe99e;',
            'bank-logo-bankofbeijing': '&#xe99f;',
            'bank-logo-hkbea': '&#xe9ac;',
            'bank-logo-hrbcb': '&#xe9ad;',
            'bank-logo-hzbank': '&#xe9b2;',
            'bank-logo-hsbank': '&#xe9b3;',
            'bank-logo-bankcomm': '&#xe9a0;',
            'bank-logo-njcb': '&#xe9a1;',
            'bank-logo-nbcb': '&#xe9a2;',
            'bank-logo-spdb': '&#xe9a3;',
            'bank-logo-pingan': '&#xe9a8;',
            'bank-logo-cmbc': '&#xe9a9;',
            'bank-logo-hxb': '&#xe9aa;',
            'bank-logo-hebbank': '&#xe9ab;',
            'bank-logo-cgbchina': '&#xe9a4;',
            'bank-logo-cebbank': '&#xe9a5;',
            'bank-logo-qdccb': '&#xe9a6;',
            'bank-logo-psbc': '&#xe9a7;',
          '0': 0
        };
        delete icons['0'];
        window.icomoonLiga = function (els) {
            var classes,
                el,
                i,
                innerHTML,
                key;
            els = els || document.getElementsByTagName('*');
            if (!els.length) {
                els = [els];
            }
            for (i = 0; ; i += 1) {
                el = els[i];
                if (!el) {
                    break;
                }
                classes = el.className;
                if (/ks-icon/.test(classes)) {
                    innerHTML = el.innerHTML;
                    if (innerHTML && innerHTML.length > 1) {
                        for (key in icons) {
                            if (icons.hasOwnProperty(key)) {
                                innerHTML = innerHTML.replace(new RegExp(key, 'g'), icons[key]);
                            }
                        }
                        el.innerHTML = innerHTML;
                    }
                }
            }
        };
        window.icomoonLiga();
    }
}());
